### ISSUE TITLE
The requirement of the public connection to provision R1soft server

### ISSUE THREAD

**Issue by khayama-zz** [IBM-Bluemix-Docs/Backup#1]
There must be the caution that the public connection have to be opened to be provisioned with R1soft.
I guess a lot of users have asked to the support with this issue, so you have to update the fact with the following link.

Configure network ports - Server Backup - Server Backup Manager: Wiki | Knowledge Base | Support
http://wiki.r1soft.com/display/ServerBackup/Configure+network+ports

**Comment by bpersich** [comment]
This issue was moved with the topic to bare-metal software. It is now here:
https://github.com/IBM-Bluemix-Docs/software/issues/1

This issue can be closed.
