### ISSUE TITLE
There is no username keyword on the cloud backup page

### ISSUE THREAD

**Issue by bbushvt** [IBM-Bluemix-Docs/Backup#10]
The documentation say to go to the cloud backup page and "Select the username of the IBM Cloud account", however there is no username keyword on that page
![image](https://user-images.githubusercontent.com/1264513/127376044-82604fb5-cce8-4dae-86ad-343c8f32966f.png)
![image](https://user-images.githubusercontent.com/1264513/127376072-64132e5d-55bb-4399-8975-191dee773a1b.png)

I understand that its likely "Instance name" is the username, however there is no way to tell other than trail and error.  This should be spelled out explicitly.  *IF* its the case that Instance name is user name, modify the documentation to say that the Instance Name will be the username to use in the WebCC Portal.

**Comment by vickmuir** [comment]
Thank you for your feedback. The documentation has been updated to match the changes in the UI.
