### ISSUE TITLE
Cloud Backup username

### ISSUE THREAD

**Issue by stevenolin** [IBM-Bluemix-Docs/Backup#11]
Can you put a label on the Cloud Backup username or move it under the Details section with a label so people will know what the user name they need to use is.

Thanks

**Comment by vickmuir** [comment]
That sounds more like a UI change request and not a Docs issue. I let the UI team know. 
I have also updated our documentation to help the users with identifying their IBM Cloud Backup user names
See https://cloud.ibm.com/docs/Backup?topic=Backup-changePassword#viewBackupPW for example.
