### ISSUE TITLE
Docs index page should list Backup for VPC under storage section

### ISSUE THREAD

**Issue by mekaufman** [IBM-Bluemix-Docs/Backup#12]
In the main index of IBM cloud catalog products under the storage section there should be a listing for 'Backup for VPC" Currently only IBM Backup is listed, which is the Classic service. Also the docs for that service make no mention of Backup for VPC. Given the strategic importance of VPC we should ensure that customers can find these new capabilities and that they get significant mention and attention whenever possible

All product docs / index https://cloud.ibm.com/docs?tab=all-docs
Backup Classic https://cloud.ibm.com/docs/Backup?topic=Backup-getting-started#getting-started
Backup for VPC https://cloud.ibm.com/docs/vpc?topic=vpc-backup-service-about

This was originally opened by @bdubwalters in the overview repo https://github.com/ibm-cloud-docs/overview/issues/5. Opening here for the correct team to address the issue.

**Comment by vickmuir** [comment]
The two products are not the same product with two different implementations. They serve the same purpose, but they are two different solutions entirely. In the same way as [Veeam on IBM Cloud](https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeamvm_overview) does backup and recover for VMWare, yet it is not a Storage product and not listed under Storage. 
IBM Cloud Backup is based on Carbonite's Evault vaults that are hosted on storage devices in the backplane and Backup software agents installed on virtual or bare-metal hosts which send data to the vaults.
Backup for VPC is actually just a snapshot of the VPC Storage volume. There's no separate software installed or portal involved. Backup for VPC is not listed under Storage in All Docs, but neither is Block Storage for VPC or File Storage for VPC. They are all included in Virtual Private Cloud (VPC) under Networking.

**Comment by bdubwalters** [comment]
hey thanks for the response.  I'll talk with product management on this as i think we need to be designing pages like this for outside in vs based on our org structure.  While Block Storage for VPC is indeed a software construct and part of VPC it definitely doesn't fall into the network category and the world thinks of it as storage.

**Comment by vickmuir** [comment]
I don't disagree with that. I think Block Storage for VPC and File Storage for VPC should have their own tiles under Storage as well, since they are Storage products, too. But it's not up to me.
