### ISSUE TITLE
Please add this into FAQ - What happens to the IBM Cloud backup after the server cancellation?

### ISSUE THREAD

**Issue by kanahavel** [IBM-Bluemix-Docs/Backup#13]
What happens to the backup created for a server after cancellation? Can the customer keep the backup itself and use it for future restores?

Answer : No customer cannot keep the backup data . Once server is cancelled the backup will be removed within 24 hours.

**Comment by vickmuir** [comment]
Thank you for your feedback. It's been transferred to our internal tracking tool for evaluation and implementation.

**Comment by vickmuir** [comment]
FAQ and https://cloud.ibm.com/docs/Backup?topic=Backup-cancelBackup updates have been published.

**Comment by kanahavel** [comment]
@vickmuir please check the "cancelled" spelling in the FAQ.

**Comment by vickmuir** [comment]
Both spellings are correct; Americans favor canceled (one L), while cancelled (two Ls) is preferred in British English and other dialects.
