### ISSUE TITLE
Suggestion: Add explicit details related to Cloud Backup file filtering.

### ISSUE THREAD

**Issue by joshua-blueteam** [IBM-Bluemix-Docs/Backup#14]
# File filtering example including file exclusions
### Below is an example of excluding every 'write.lock' and 'node.lock' file from an Opensearch NFS directory:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/110563610/202354689-2c647488-43fc-4ae3-b224-a2319bd73f93.png">

**Comment by vickmuir** [comment]
Moved the issue to GHE to work on it. This repo is just a mirror.

**Comment by vickmuir** [comment]
@joshua-blueteam - which topic were you reading before you submitted this suggestion? I have multiple topics that mention exclusions, but I feel like this is not about one of them.

**Comment by vickmuir** [comment]
https://cloud.ibm.com/docs/Backup?topic=Backup-configureFileBackup was updated yesterday.
