### ISSUE TITLE
FAQ deleting entire/whole backups jobs

### ISSUE THREAD

**Issue by gaskinner84** [IBM-Bluemix-Docs/Backup#16]
Good day all - I notice there is no information on how to delete backup jobs for IBM Cloud backups. 

We would like an FAQ created on how to achieve this here: https://cloud.ibm.com/docs/Backup?topic=Backup-faqs

IE: Classic Infrastructure > Cloud Backups > *select instance name* > Backup > Task (Backup server name) > select "minus" symbol next to the task name

![image](https://github.com/ibm-cloud-docs/Backup/assets/46956547/6f23e6a3-af2a-42f8-bc7e-0854d85803a1)

The above is the only method for customers to remove entire jobs/data from IBM Cloud Backup. 

Note: Removing jobs from the IBM Cloud Backup UI (webcc) will not result in data removal. 
Note: If customers would like to delete specific safe sets (not the entire job), they should review: https://cloud.ibm.com/docs/Backup?topic=Backup-faqs#deletesafeset

Regards,

Gary S.
ACS-Storage Support Lead
IBM Cloud Support

**Comment by vickmuir** [comment]
Created a new topic for this: https://test.cloud.ibm.com/docs/Backup?topic=Backup-deletetasks. I asked the Backup Ops team to review. When they approve, I will publish the update. 
This work is also tracked in JIRA [DOCS-7072](https://jira.softlayer.local/browse/DOCS-7072)
