### ISSUE TITLE
How to upgrade R1soft Server Backup Manager

### ISSUE THREAD

**Issue by khayama-zz** [IBM-Bluemix-Docs/Backup#2]
Please update and document this topic in IBM Cloud Docs.
For the case of Vyatta, it's documented as follows.

Upgrade the OS
https://console.bluemix.net/docs/infrastructure/virtual-router-appliance/upgrade-os.html#upgrade-the-os

The users may have to contact IBM Cloud support to get the latest binary and upgrade.

**Comment by bpersich** [comment]
This issue was moved with the topic to bare-metal software. It is now here:
https://github.com/IBM-Bluemix-Docs/software/issues/2

This issue can be closed.

**Comment by khayama-zz** [comment]
Please add how to upgrade R1soft Server Backup Manager to IBM Cloud Docs.
For example, How can we get the upgrade binary?

**Comment by bpersich** [comment]
@khayama. Please open any further R1Soft issues here:
https://github.com/IBM-Bluemix-Docs/software
