### ISSUE TITLE
SQL Server plug-in support Linux MSSQL Server 2017?

### ISSUE THREAD

**Issue by ArielZhang** [IBM-Bluemix-Docs/Backup#5]
I want to ask if the backup plugin supports MSSQL Server 2017 in Linux.

**Comment by vickmuir** [comment]
The SQL plug-in is only offered in the Windows Environment. It is not available for MSSQL Server 2017 in Linux.

**Comment by ArielZhang** [comment]
do you have any plan to support Linux mssql? @vickmuir
