### ISSUE TITLE
Can you add how to restart Evault back Agents in the FAQ section ?

### ISSUE THREAD

**Issue by kanahavel** [IBM-Bluemix-Docs/Backup#6]
Hello Team

I am kanak from ACS Storage support team. Often we do receive a request from the customer on "How to restart the Evault backup agents?" Or "How to debug the backup agents?" . This request for Windows and Linux.. 

Unfortunately, The IBM Cloud backup document doesn't cover the above topics - https://cloud.ibm.com/docs/Backup?topic=Backup-getting-started. 

Even the FAQ section doesn't have the above topics. So we normally share the Evault document / URL with the customer. 

How to Troubleshoot an Agent that shows Offline in Portal - https://support.carbonite.com/evault/articles/HOW-Troubleshoot-an-Agent-that-shows-Offline-in-Portal

How to Troubleshoot Linux or AIX Agent shows offline in Portal - https://support.carbonite.com/evault/articles/All-Linux-agent-shows-offline-on-webcc-or-portal

Having said that , it would be nice to have the above information / URL in FAQ section. So that we can share the IBM Cloud Doc URL to the customer rather than sharing Evault URL.

Thanks

**Comment by vickmuir** [comment]
I have converted this to a JIRA issue and will work on the requested updates.
https://jira.softlayer.local/browse/DOCS-6194

**Comment by vickmuir** [comment]
Created offline-agent-linux.md and offline-agent-windows.md. I will review with the Backup Operations team tomorrow to ensure the content is accurate.

**Comment by vickmuir** [comment]
https://test.cloud.ibm.com/docs/Backup?topic=Backup-troubleshoot-LinuxAgent
https://test.cloud.ibm.com/docs/Backup?topic=Backup-troubleshoot-WinAgent
^^ these documents are ready for review.

**Comment by vickmuir** [comment]
New topics are published.
