### ISSUE TITLE
Can we add instruction on how to uninstall and reinstall the agent?

### ISSUE THREAD

**Issue by kanahavel** [IBM-Bluemix-Docs/Backup#9]
Hello Team 

Can we include the instruction on how to uninstall and reinstall the webCC agent please? Because we often found out that customer may did something wrong during the installation and that requires uninstall and reisntall. 

We do not have any instruction on the IBM cloud document for this.

**Comment by vickmuir** [comment]
Thank you for your feedback. I notified the support team and created a JIRA issue to track the work internally.

**Comment by vickmuir** [comment]
New FAQ and instructions are available:
- https://cloud.ibm.com/docs/Backup?topic=Backup-faqs#agent-uninstall
- https://cloud.ibm.com/docs/Backup?topic=Backup-cancelBackup#uninstallbackupagent
